### ISSUE TITLE
Llama.cpp Support

### ISSUE THREAD

**Issue by loretoparisi** [persimmon-ai-labs/adept-inference#6]
Exploring possibilities to support [GGML / GGUF](https://github.com/ggerganov/ggml) formats to run with [Llama.cpp](https://github.com/ggerganov/llama.cpp)

**Comment by VincentJGeisler** [comment]
the model is missing some keys and count be converted to GGUF format 

'rms_norm_eps'

**Comment by maddes8cht** [comment]
A full set of Llama.cpp compatible .gguf files is available at
https://huggingface.co/maddes8cht/adept-persimmon-8b-base-gguf
and
https://huggingface.co/maddes8cht/adept-persimmon-8b-chat-gguf
For the moment, cuda accelleration seems not to work, so you need to use `-ngl 0` with the cublas versions.
